#Demo Spring application

trigger:
 branches:
    include:
      - master
pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'BuildArtifact'
    displayName: ' Building Artifact'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'Building Artifact'
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            options: '--no-transfer-progress'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(agent.builddirectory)/s/target'
            Contents: '*.jar'
            TargetFolder: '$(build.artifactstagingdirectory)'
            CleanTargetFolder: true
            OverWrite: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          displayName: 'Publish Artifact'
          
        -
- task: WhiteSource@21
  inputs:
    projectName: 'gitlab21.Azuredevopsdemo-spring'